import { K2D } from "next/font/google";
import "./globals.css";

// Fuente K2D auto-hospedada con next/font (sin FOUT)
const k2d = K2D({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={k2d.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
